version: "3.8"

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - target: 80
        published: 8000

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./api:/usr/app
    environment:
      MYSQL_HOST_IP: mysql_db
      API_PORT: $API_PORT

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        REACT_APP_API_BASE_URL: $CLIENT_API_BASE_URL
        WDS_SOCKET_HOST: $NGINX_HOST
        WDS_SOCKET_PORT: $NGINX_PORT
    volumes:
      - /app/node_modules
      - ./client:/usr/app
